### ISSUE TITLE
Version one has 404 at http://adel.eurecom.fr/api/

### ISSUE THREAD

**Issue by shakeel26** [jplu/ADEL#2]
Hello, 
Its mentioned in doc that Version 2 is under development annd version one demo is at http://adel.eurecom.fr/api/. while it has 404, Can you please fix the issue and if possible please share user manual. I need to try ADEL to find duplications in dataset.

Thanks

**Comment by jplu** [comment]
Hello,

Currently I do not have access to the server where the v1 was deployed, so for now I cannot put back the demo online. Hence, if you need to use ADEL v1 I propose that you download the v1 release source code and to compile it, in order to be able to use it.

**Comment by rtroncy** [comment]
Hello @shakeel26 
Indeed, we had to work on our server infrastructure but a public instance of the ADEL API will be resumed shortly at http://adel.eurecom.fr/api/

**Comment by shakeel26** [comment]
Thanks @jplu , Can you please let me know If version2 is ready for duplicates detection ? if yes please share user manual, I don't find much information about the running of ADEL, Thanks

**Comment by jplu** [comment]
What do you call duplicates detection? If you want the documentation you have a complete README.

**Comment by shakeel26** [comment]
By duplicates I mean duplicate I mean records/triples/statements in datasets/ graphs.

**Comment by jplu** [comment]
Ok so if I understand, what you are looking for is to find duplicate triples in a graph, right ?

If it is what you meant, ADEL do not allow you to do that, sorry.

**Comment by jplu** [comment]
The website is back online.
